force-app/main/default/objects/JSON_Generator_Setting__mdt/JSON_Generator_Setting__mdt.object-meta.xml
<CustomObject>
    <label>JSON Generator Setting</label>
    <pluralLabel>JSON Generator Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/JSON_Generator_Setting__mdt/fields/Add_if_Null__c.field-meta.xml
<CustomField>
    <fullName>Add_if_Null__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Include in JSON if value is null.</description>
    <label>Add if Null</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JSON_Generator_Setting__mdt/fields/JSON_Element_Type__c.field-meta.xml
<CustomField>
    <fullName>JSON_Element_Type__c</fullName>
    <description>Value Element type.</description>
    <label>JSON Element Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Map</fullName>
                <default>true</default>
                <label>Map</label>
            </value>
            <value>
                <fullName>List</fullName>
            </value>
            <value>
                <fullName>MapValueElement</fullName>
            </value>
            <value>
                <fullName>ListValueElement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JSON_Generator_Setting__mdt/fields/JSON_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>JSON_Field_Name__c</fullName>
    <description>JSON field name to be included in JSON</description>
    <label>JSON Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JSON_Generator_Setting__mdt/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>Unique identifier in JSON Setting Name group to identify parent record.</description>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JSON_Generator_Setting__mdt/fields/Parent_Key__c.field-meta.xml
<CustomField>
    <fullName>Parent_Key__c</fullName>
    <description>Specify parent unique identifier to maintain JSON hierarchy.</description>
    <label>Parent Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JSON_Generator_Setting__mdt/fields/Setting_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Setting_Group_Name__c</fullName>
    <description>It is used to identify the group of setting records belongs to same JSON request.</description>
    <inlineHelpText>It is used to identify the group of setting records belongs to same JSON request.</inlineHelpText>
    <label>Setting Group Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JSON_Generator_Setting__mdt/fields/SObject_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Field_API_Name__c</fullName>
    <description>Provide salesforce object field api name from base Sobject.</description>
    <label>SObject Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JSON_Generator_Setting__mdt/fields/Value_Default__c.field-meta.xml
<CustomField>
    <fullName>Value_Default__c</fullName>
    <description>Incase you want to hard-code default value.</description>
    <label>Value - Default</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JSON_Generator_Setting__mdt/fields/Value_Element_Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Value_Element_Data_Type__c</fullName>
    <label>Value Element Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
                <default>true</default>
                <label>String</label>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JSONGeneratorSettingSelector.cls
public with sharing class JSONGeneratorSettingSelector {

    public List<JSON_Generator_Setting__mdt> getSettingByGrpName(String settingGroupName) {

        return [SELECT Id,
                        Add_if_Null__c,
                        Value_Element_Data_Type__c,
                        JSON_Element_Type__c,
                        JSON_Field_Name__c,
                        Key__c,
                        Parent_Key__c,
                        Setting_Group_Name__c,
                        SObject_Field_API_Name__c,
                        Value_Default__c
                FROM JSON_Generator_Setting__mdt
                WHERE  Setting_Group_Name__c =:settingGroupName];

    }


    public List<JSON_Generator_Setting__mdt> getSObjectFieldsByGrpName(String settingGroupName) {

        return [SELECT Id,
                        SObject_Field_API_Name__c
                FROM JSON_Generator_Setting__mdt
                WHERE  Setting_Group_Name__c =:settingGroupName];

    }
}